### ISSUE TITLE
JavaScript to TypeScript

### ISSUE THREAD

**Issue by joachimsalim** [joachimsalim/the-chookbook#4]
Convert the JavaScript source code to TypeScript in its Node.js runtime environment within the Express.js framework.

The other option would be to rewrite the project in the [NestJS](https://docs.nestjs.com/microservices/basics) framework with its microservices package.

**Comment by RMarmolejo90** [comment]
I'm interested to know the reasoning behind this. This is an honest question. If the code is already written in javascript, and typescript compiles down to javascript, why are you converting your javascript to typescript? Are there type errors that need to be fixed? Or are you trying to utilize typescripts static typing and interfaces for a more object oriented architecture?

**Comment by i8abyte** [comment]
> I'm interested to know the reasoning behind this. This is an honest question. If the code is already written in javascript, and typescript compiles down to javascript, why are you converting your javascript to typescript? Are there type errors that need to be fixed? Or are you trying to utilize typescripts static typing and interfaces for a more object oriented architecture?

I'm trying to utilize TypeScript's static typing and interfaces for a more object-oriented architecture. This also gives me an opportunity to learn NestJS and its microservices package.

**Comment by i8abyte** [comment]
> I'm interested to know the reasoning behind this. This is an honest question. If the code is already written in javascript, and typescript compiles down to javascript, why are you converting your javascript to typescript? Are there type errors that need to be fixed? Or are you trying to utilize typescripts static typing and interfaces for a more object oriented architecture?

I'm trying to utilize TypeScript's static typing and interfaces for a more object-oriented architecture.
